### ISSUE TITLE
centered text with literalinclude

### ISSUE THREAD

**Issue by cursorius-cursor** [iktakahiro/sphinx_theme_pd#5]
I use the following source code and the text is centered. It should be an the left side as with ::

.. literalinclude:: files/verzeichnisse.tex
   :language: latex
   :linenos:

**Comment by iktakahiro** [comment]
Thank you for your feedback. I'll check it.

**Comment by iktakahiro** [comment]
Hi,

This is the problem that occurred as a result of :lineos: .

Fixed, see below.

<img width="843" alt="code-block" src="https://cloud.githubusercontent.com/assets/1491856/10024047/373aefde-6190-11e5-8df7-dac3fce6d5db.png">
